url: "https://eacrawford02.github.io/My-Website/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: "Ewen Crawford" # the name of your site, e.g. ACME Corp.
author: "Ewen Crawford"
